apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.inputs.dbVolumeClaimGreen.name }}
spec:
  resources:
    requests:
      storage: {{ .Values.inputs.dbVolumeClaimGreen.storage }}
  volumeMode: {{ .Values.inputs.dbVolumeClaimGreen.volumeMode }}
  storageClassName: {{ .Values.inputs.storageClass.name }}
  accessModes:
    {{- range .Values.inputs.dbVolumeClaimGreen.accessModes }}
    - {{ . }}
    {{- end }}