apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inputs.dbServiceBlue.name }}
spec:
  type: {{ .Values.inputs.dbServiceBlue.type }}
  selector:
    app: postgres-blue
  ports:
  - port: {{ .Values.inputs.dbServiceBlue.ports.port }}
    targetPort: {{ .Values.inputs.dbServiceBlue.ports.targetPort }}